In [17]:
import dash
import dash_core_components as dcc
import dash_html_components as html
import pandas as pd

In [18]:
# Use a css file from your GitHub Pages site 
external_stylesheets = ['https://mangaln.github.io/style.css']

In [19]:
# Creates the app to instantiate the content for the Dashboard and use the external_stylesheets
app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

In [20]:
# Use a csv dataset from a repository in your GitHub account. Use the Raw URL to expose the data to the Python dataframe
df = pd.read_csv('https://raw.githubusercontent.com/mangaln/data/master/us-counties.csv')

In [21]:
df=df.drop(columns='date')

In [22]:
df1 = df.groupby(["county","state"]).cases.sum().reset_index()
df2=df.groupby(["county","state"]).deaths.sum().reset_index()
df=pd.concat([df1,df2.deaths],axis=1)
df.head()

      county           state  cases  deaths
0  Abbeville  South Carolina    224       0
1     Acadia       Louisiana   2008      89
2   Accomack        Virginia    429       1
3        Ada           Idaho  10841     148
4      Adair            Iowa     36       0

In [23]:
df=df.sort_values(by=['deaths'], ascending=False)
df.head()

             county     state    cases  deaths
1822  New York City  New York  2290623  129442
1803         Nassau  New York   502133   19523
2684          Wayne  Michigan   236595   14301
561            Cook  Illinois   311574   10301
2709    Westchester  New York   448465   10219

In [37]:
(df.deaths.sum()/df.cases.sum())*100

3.8580393291112776

In [28]:
# Custom function used to generate a data table from a dataframe
def generate_table(dataframe, max_rows=16):
    return html.Table([
        html.Thead(
            html.Tr([html.Th(col) for col in dataframe.columns])
        ),
        html.Tbody([
            html.Tr([
                html.Td(dataframe.iloc[i][col]) for col in dataframe.columns
            ]) for i in range(min(len(dataframe), max_rows))
        ])
    ])
# Add content to the app layout
# Begin all content DIV
app.layout=html.Div([
    # Add your HTML tags to the content - notice a comma is added between HTML elements
    html.H1('Data Visualization for Story Telling'),
    html.Div([
        html.P('Corona Cases vs Deaths in US counties'),
    ]),
    # Begin of DIV surrounding both Tables
    html.Div([
    # Begin of First Table
    html.Table(style={'width':'100%'},
               # Begin of Table children
               children=[
                   #######################################################################
                   # Begin of First Tr
                 html.Tr(
                     #Begin Tr children
                     children=[
                         # Begin Th
                         
                         html.Th(style={'width':'30%'},
                             # Begin Th children
                             children=[
                                 html.H3('Total Cases vs Deaths in US')
                             # End of Th children   
                             ]
                         
                         # End of Th - Notice a comma is placed here to separate the next Th
                         ),
                         # Begin of Th
                         html.Th(style={'width':'70%'},
                             # Begin of Th children
                             children=[
                                 html.H3('Corona Deaths vs cases statewise')
                             # End of Th children    
                             ]
                         
                         # End of Th
                         )
                         
                     # End of Tr children    
                     ]
                 # End of First Tr - Notice a comma is placed here to separate the next Tr
                 ),
                 #########################################################################
                 # Begin of Second Tr
                 html.Tr(
                     #Begin Tr children
                     children=[
                         # Begin Td
                         html.Td(
                             # Begin Td children
                             children=[
                                    # Display bar graph
                                    dcc.Graph(
                                    id='example-graph',
                                    figure={
                                        'data': [
                                            {'x': [1, 2, 3], 'y': [4, 1, 2], 'type': 'bar', 'name': 'Cases'},
                                            {'x': [1, 2, 3], 'y': [2, 4, 5], 'type': 'bar', 'name': 'Deaths'},
                                        ],
                                        'layout': {
                                            'title': 'Cases vs Deaths'
                                        }
                                    }
                                # End of Chart 1
                                )
                              # End of Td children   
                             ]
                         
                         # End of Td - Notice a comma is placed here to separate the next Th
                         ),
                         # Being of Td
                         html.Td(
                             # Begin of Td children
                             children=[
                                 # Display plot graph use data from dataframe df
                                 dcc.Graph(
                                    id='life-exp-vs-gdp',
                                figure={
                                    'data': [
                                        dict(
                                            x=df[df['state'] == i]['cases'],
                                            y=df[df['state'] == i]['deaths'],
                                            text=df[df['state'] == i]['county'],
                                            mode='markers',
                                            opacity=0.7,
                                            marker={
                                                'size': 15,
                                                'line': {'width': 0.5, 'color': 'white'}
                                            },
                                            name=i
                                        ) for i in df.state.unique()
                                    ],
                                    'layout': dict(
                                        xaxis={'type': 'log', 'title': 'Cases'},
                                        yaxis={'title': 'Deaths'},
                                        margin={'l': 40, 'b': 40, 't': 10, 'r': 10},
                                        legend={'x': 0, 'y': 1},
                                        hovermode='closest'
                                    ), 'layout': {
                                            'title': 'Deaths by state'}
                                    # End of 2nd Inner DIV
                                    })
                           
                             # End of Td children    
                             ]
                         # End of Td
                         )
                     # End of Tr children    
                     ]
                 # End of Tr
                 )     
                #########################################################################                   
               #End of Table Children    
               ]
              # End of First Table - Notice a comma is placed here to separate the next Table
              ),
    
    #########################################################################################   
    # Begin of Second Table
    html.Table(style={'width':'100%'},
               children=[
                 #######################################################################
                 # Begin First Tr
                 html.Tr(
                     #Begin Tr children
                     children=[
                         # Begin Th
                         html.Th(style={'width':'30%'},
                             # Begin Th children
                             children=[
                                 html.H3('2020 Impact of Corona on US')
                             # End of Th children   
                             ]
                         
                         # End of Th - Notice a comma is placed here to separate the next Th
                         ),
                         #Begin of Th
                         html.Th(style={'width':'10%'},
                             # Begin of Th children
                                 children=[
                                 # Nothing to display here, just a place holder in the column
                                 html.H2('')
                                 # End of Th children    
                                 ]
                             # End of Th - Notice a comma is placed here to separate the next Th
                         ),
                         # Begin of Th
                         html.Th(style={'width':'70%'},
                             # Begin of Th children
                             children=[        
                                    html.H3('Top 15 affected US states ')
                                                               
                             # End of Th children    
                             ]
                         # End of Th
                         )
                     # End of Tr children    
                     ]
                 # End of First Tr
                 ),
                   
                ######################################################################
                # Begin of Second Tr
                 html.Tr(
                     #Begin Tr children
                     children=[
                         # Begin Td
                         html.Td(
                             # Begin Td children
                             children=[
                                    # Display a simple line graph
                                    dcc.Graph(
                                        id='g1', 
                                        figure={'data': [{'y': [1, 2,3]}], 
                                                'layout': {'title': 'Corona Impact on US'}})
                             # End of Td children   
                             ]
                         
                         # End of Td - Notice a comma is placed here to separate the next Th
                         ),
                         # Begin of Td
                         html.Td(style={'border':'1px solid black'},
                             # Begin of Td children
                             children=[
                                 # Display a large and important measure
                                 html.H2('Deaths'),
                                 html.H2('vs Cases:'),
                                 html.H2('3.85%')
                             # End of Td children    
                             ]
                         # End of Td
                         ),
                         
                         # Begin of Td
                         html.Td(
                             # Begin of Td children
                             children=[
                                    # Execute custom generate_table function and display data
                                    # Use data from dataframe df2
                                    generate_table(df)
                             # End of Td children    
                             ]
                         # End of Td
                         )
                     # End of Tr children    
                     ]
                 # End of Second Tr
                 )     
               
               #######################################################################
               #End of Table Children    
               ]
              #########################################################################################
              # End of Second Table - Notice a comma is placed here to separate the next Content
              ),
    # End of DIV surrounding both Tables
    ]),
               
# End of all content DIV
])

# Run the app on the web server
if __name__ == '__main__':
    # Set debug to False. Some configurations are not setup for Debug
    app.run_server(debug=False)

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [24/Apr/2020 15:36:49] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [24/Apr/2020 15:36:50] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [24/Apr/2020 15:36:50] "GET /_dash-layout HTTP/1.1" 200 -